services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - app3

  app1:
    image: httpd:alpine
    volumes:
      - ./app1:/usr/local/apache2/htdocs/

  app2:
    image: httpd:alpine
    volumes:
      - ./app2:/usr/local/apache2/htdocs/
  app3:
    image: httpd:alpine
    volumes:
      - ./app3:/usr/local/apache2/htdocs/